#!/usr/bin/env bash
# ai-paths.sh — show or sync portable paths for multi-machine (Mac + Ubuntu)
#
# Usage:
#   ai-paths              # show resolved paths for cwd project
#   ai-paths check          # exit 1 if AI_DEV_OS_HOME not resolvable
#   ai-paths sync           # write ai-dev-os.local.yaml from current machine (gitignored)
#   ai-paths machine-setup  # print shell exports for this machine
#
set -euo pipefail

_self="${BASH_SOURCE[0]}"
while [[ -L "$_self" ]]; do
  _dir="$(cd -P "$(dirname "$_self")" && pwd)"
  _self="$(readlink "$_self")"
  [[ $_self != /* ]] && _self="$_dir/$_self"
done
OS_REPO="$(cd "$(dirname "$_self")/.." && pwd)"
# shellcheck source=resolve-os-paths.sh
source "$OS_REPO/scripts/resolve-os-paths.sh"

die() { echo "ERROR: $1" >&2; exit 1; }
info() { echo "  $1"; }

cmd="${1:-show}"
project_dir="$(pwd)"

resolve_os_paths "$project_dir"

case "$cmd" in
  show)
    echo "=== AI Dev OS — resolved paths ==="
    echo "  machine:    $(uname -s) $(hostname 2>/dev/null || echo local)"
    echo "  OS home:    ${AI_DEV_OS_HOME_RESOLVED:-<not set — run install-cli.sh>}"
    echo "  project:    ${PROJECT_ROOT_RESOLVED}"
    if [[ -n "${AI_DEV_OS_HOME:-}" ]]; then
      echo "  env:        AI_DEV_OS_HOME=$AI_DEV_OS_HOME"
    fi
    if [[ -f "$project_dir/ai-dev-os.local.yaml" ]]; then
      echo "  local:      $project_dir/ai-dev-os.local.yaml"
    fi
    ;;
  check)
    resolve_os_paths "$project_dir"
    [[ -n "${AI_DEV_OS_HOME_RESOLVED:-}" && -d "${AI_DEV_OS_HOME_RESOLVED}" ]] \
      || die "AI_DEV_OS_HOME not set. Run: $OS_REPO/scripts/install-cli.sh"
    info "OK — $AI_DEV_OS_HOME_RESOLVED"
    ;;
  sync)
    [[ -f "$project_dir/ai-dev-os.yaml" || -f "$project_dir/AGENTS.md" ]] \
      || die "Not an OS-bound project (no ai-dev-os.yaml or AGENTS.md)"
    [[ -n "${AI_DEV_OS_HOME:-}" ]] || die "Set AI_DEV_OS_HOME first (install-cli.sh)"
    local_file="$project_dir/ai-dev-os.local.yaml"
    cat > "$local_file" <<EOF
# Generated by ai-paths sync on $(hostname) — gitignored, safe per machine
# Primary config is still env:AI_DEV_OS_HOME in ai-dev-os.yaml
ai_dev_os_home: $AI_DEV_OS_HOME
project_root: $PROJECT_ROOT_RESOLVED
generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
host: $(hostname 2>/dev/null || echo unknown)
EOF
    info "Wrote $local_file"
    ;;
  machine-setup)
    shell_rc=""
    if [[ -n "${ZSH_VERSION:-}" ]] || [[ "$SHELL" == *zsh* ]]; then
      shell_rc="$HOME/.zshrc"
    else
      shell_rc="$HOME/.bashrc"
    fi
    echo "# Add to $shell_rc (this machine only):"
    echo "export AI_DEV_OS_HOME=\"$OS_REPO\""
    echo "export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo "alias ai-new=\"\$AI_DEV_OS_HOME/scripts/new-project.sh\""
    ;;
  -h|--help)
    cat <<EOF
ai-paths — multi-machine path resolution (Mac / Ubuntu)

  ai-paths show           Resolved paths (default)
  ai-paths check          Fail if OS home missing
  ai-paths sync           Write ai-dev-os.local.yaml for this machine
  ai-paths machine-setup  Print shell exports

Per machine: run install-cli.sh once. Per project: ai-new (portable yaml).
EOF
    ;;
  *)
    die "Unknown command: $cmd (try ai-paths --help)"
    ;;
esac